version: "2"
services:
  frontend:
    container_name: frontend
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: frontend-angular2:2
    ports:
    - "3000:3000"
    - "3001:3001"
    - "8080:8080"
    volumes:
    - "../:/workspace"
    working_dir: /workspace
    command: ["/workspace/docker/init.sh"]
